In [1]:
import numpy as np
import sys
sys.path.append("./hilbert")
from hilbert.Hilpy import Hilpy
import matplotlib.pyplot as plt
%matplotlib inline
import math

ModuleNotFoundError: No module named 'matplotlib.pyplot'

In [ ]:
vec1 = np.zeros(100)+2+3j
sf1 = Hilpy.to_vector(vec1)
vec2 = np.zeros(100)+3+2j
sf2 = Hilpy.to_vector(vec2)

In [2]:
sf3 = sf1+sf2

NameError: name 'sf1' is not defined

In [3]:
sf3.plot_vector()

NameError: name 'sf3' is not defined

In [88]:
x = np.array([[-15, 12],
              [15, -12],])

In [87]:
np.linalg.eig(x)

(array([-1.80000000e+01, -1.77635684e-15]),
 array([[-0.70710678, -0.62469505],
        [ 0.70710678, -0.78086881]]))

In [89]:
np.linalg.eig(x)

(array([-2.70000000e+01, -1.77635684e-15]),
 array([[-0.70710678, -0.62469505],
        [ 0.70710678, -0.78086881]]))