In [1]:
import numpy as np

In [32]:
def relu(x) :
    return np.maximum(0,x)

In [99]:
M = np.array([
    [1,1], 
    [1,0], 
    [0,1], 
    [0,1], 
    [0,1], 
])

M_ = np.array([
    [1 , 0, 0, 0], 
    [-1, 0, 0, 0], 
    [-1, 1, 0, 1], 
    [0 ,-1, 1,-1], 
    [0 , 0,-1, 0], 
])

m_c = np.array([
    [0.2,], 
    [0.3,],
])

S = np.array([
    [-2,0 ], 
    [-3,0 ], 
    [1 ,0 ], 
    [0 ,1 ], 
    [0 ,1 ], 
])

D = np.array([
    [0 ,1 ], 
    [1 ,0 ],  
])

x = np.array([
    [2], 
    [3], 
    [1], 
    [2], 
    [5], 
])

p = np.array([
    [0], 
    [0], 
    [0], 
    [0], 
    [0], 
])

x_h = np.array([
    [0], 
    [0], 
    [0], 
    [0], 
    [3], 
])


h = np.array([
    [0], 
    [0], 
    [0], 
    [0], 
    [2], 
])


a = -np.log(np.array([
    [4], 
    [1], 
    [2], 
    [1], 
    [3], 
]))

k = np.array([
    [1], 
    [0.7], 
    [0.1], 
    [0],  
])

v = np.array([
    [0], 
    [0], 
    [0], 
    [0.8],  
])

c = np.array([
    [0], 
    [0], 
    [0], 
    [3],  
])

In [100]:
V = np.dot(np.dot(S,1/(D+1)-1) , S.T)

m = np.dot(M,m_c)

G_x = np.log(x.T)+a.T+np.dot(x.T, V) + (p*p/(2*m)).T

dx_dt = -np.dot(M_,(k.T*(np.exp(np.dot(G_x,M_))-1)*np.exp(np.dot(np.log(x.T)+a.T,relu(-M_)))).T)

dx_dt

array([[ 1.        ],
       [-1.        ],
       [ 0.3999738 ],
       [-1.43330714],
       [ 0.03333333]])

In [101]:
((np.exp(np.dot(G_x,M_))-1)*np.exp(np.dot(np.log(x.T)+a.T,relu(-M_)))).T

array([[-1.        ],
       [-1.99996257],
       [ 0.33333333],
       [-1.99996257]])

In [102]:
np.dot(np.dot(x.T, V), M_)

array([[ 0. , -9.5,  0. , -9.5]])

In [81]:
dx_dt

array([[ 1.        ],
       [-1.        ],
       [ 0.05      ],
       [-1.08333333],
       [ 0.03333333]])

In [66]:
(np.exp(np.dot(G_x,M_))-1)

array([[-0.87737352, -0.75      ,  0.2       , -0.75      ]])

In [67]:
np.dot(S.T,relu(M_))

array([[-2,  1,  0,  1],
       [ 0,  0,  1,  0]])

In [68]:
np.dot(S.T,relu(M_))

array([[-2,  1,  0,  1],
       [ 0,  0,  1,  0]])

In [69]:
V = np.dot(np.dot(S,1/(D+1)-1) , S.T)

In [41]:
V

array([[ 0. ,  0. ,  0. ,  1. ,  1. ],
       [ 0. ,  0. ,  0. ,  1.5,  1.5],
       [ 0. ,  0. ,  0. , -0.5, -0.5],
       [ 1. ,  1.5, -0.5,  0. ,  0. ],
       [ 1. ,  1.5, -0.5,  0. ,  0. ]])

In [27]:
temp = np.dot(x.T,V)

In [30]:
temp

array([[ 7. , 10.5, -3.5,  6. ,  6. ]])

In [39]:
np.dot(temp, relu(M_))

array([[ 7. , -3.5,  6. , -3.5]])

In [38]:
np.dot(temp, relu(-M_))

array([[7., 6., 6., 6.]])

In [9]:
a = np.array([1,2])
b = np.array([3,4])
np.dot(a,b,a)

ValueError: output array is not acceptable (must have the right datatype, number of dimensions, and be a C-Array)