In [1]:
import numpy as np
import math

In [67]:
N=5
T = np.zeros((N, N, N)) 

for x in range(N) :
    for y in range(N) :
        for z in range(N) :
            if (x+y-z)%N == 0  : T[x][y][z]=1
                
#T

In [68]:
S_AB = np.random.rand(N)


In [69]:
M_AB = np.dot(S_AB,T)

In [70]:
PI_A = np.array(range(N))

In [71]:
PI_B = np.array(range(N-1,-1,-1))

In [72]:
A = 2
B = 2
C = 3
D = 2

W = np.zeros((N, N)) 

for x in range(N) :
    for y in range(N) :
        if x<=y : W[x][y]=  A * math.pow(math.e,(x-y)*B)
        else : W[x][y]=  -C * math.pow(math.e, (x-y) * -D)
                
W

array([[ 2.00000000e+00,  2.70670566e-01,  3.66312778e-02,
         4.95750435e-03,  6.70925256e-04],
       [-4.06005850e-01,  2.00000000e+00,  2.70670566e-01,
         3.66312778e-02,  4.95750435e-03],
       [-5.49469167e-02, -4.06005850e-01,  2.00000000e+00,
         2.70670566e-01,  3.66312778e-02],
       [-7.43625653e-03, -5.49469167e-02, -4.06005850e-01,
         2.00000000e+00,  2.70670566e-01],
       [-1.00638788e-03, -7.43625653e-03, -5.49469167e-02,
        -4.06005850e-01,  2.00000000e+00]])

In [83]:
S_AB

array([0.64576602, 0.17550189, 0.07368498, 0.36184457, 0.10038898])

In [80]:
np.dot(M_AB, PI_A)

array([1.80996149, 2.66520304, 2.21316661, 3.20192814, 3.68160516])

In [78]:
np.dot(M_AB, PI_A)

array([0, 1, 2, 3, 4])

In [82]:
np.dot( np.dot(PI_A, M_AB) , np.dot(W, PI_B) )

36.45641126817882